# Generated by Django 5.0.4 on 2024-05-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
