# Generated by Django 5.0.4 on 2024-04-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='playlists',
            field=models.ManyToManyField(blank=True, related_name='groups', to='userprofile.playlist'),
        ),
    ]
