# Generated by Django 5.0.4 on 2024-05-06 08:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_group_playlists'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='waiting',
            field=models.ManyToManyField(related_name='waiting_for_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='member_of_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
