# Generated by Django 5.0.2 on 2024-03-16 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('userprofile', '0002_alter_userprofile_created_groups'),
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='access_status',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='access_status',
        ),
        migrations.AddField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('unlisted', 'Unlisted')], default='unlisted', max_length=20),
        ),
        migrations.AddField(
            model_name='playlist',
            name='status',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('unlisted', 'Unlisted')], default='unlisted', max_length=20),
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(null=True, to='user.user'),
        ),
        migrations.AlterField(
            model_name='group',
            name='videos',
            field=models.ManyToManyField(null=True, to='video.video'),
        ),
    ]
