# Generated by Django 5.0.2 on 2024-03-16 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('userprofile', '0003_remove_group_access_status_and_more'),
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, to='user.user'),
        ),
        migrations.AlterField(
            model_name='group',
            name='videos',
            field=models.ManyToManyField(blank=True, to='video.video'),
        ),
    ]
