# Generated by Django 5.0.4 on 2024-05-08 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_group_waiting_alter_group_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='created_groups',
        ),
    ]
