# Generated by Django 5.0.2 on 2024-03-16 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_alter_group_members_alter_group_videos'),
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='videos',
            field=models.ManyToManyField(blank=True, to='video.video'),
        ),
    ]
