# Generated by Django 5.0.4 on 2024-05-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_analytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytics',
            name='status',
            field=models.CharField(default='Не просмотрено', max_length=100),
        ),
    ]
