# Generated by Django 5.0.4 on 2024-05-12 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_analytics_status'),
        ('video', '0004_comment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytics',
            name='video',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='video.video'),
            preserve_default=False,
        ),
    ]
