# Generated by Django 5.0.4 on 2024-05-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0010_alter_analytics_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytics',
            name='duration',
            field=models.CharField(max_length=100),
        ),
    ]
