# Generated by Django 5.0.4 on 2024-05-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0011_alter_analytics_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytics',
            name='full_duration',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='analytics',
            name='duration',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='analytics',
            name='status',
            field=models.CharField(default='В процессе', max_length=100),
        ),
    ]
