# Generated by Django 5.0.2 on 2024-03-24 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='access_status',
            new_name='status',
        ),
    ]
