# Generated by Django 5.0.2 on 2024-03-24 18:21

import corpvideohost.yandex_s3_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_rename_access_status_video_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.FileField(storage=corpvideohost.yandex_s3_storage.ClientDocsStorage(), upload_to=''),
        ),
    ]
