# Generated by Django 5.0.2 on 2024-04-13 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_alter_video_list_favorited_by_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='list_favorited_by_user',
        ),
    ]
