# Generated by Django 5.0.2 on 2024-03-26 11:03

import video.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_alter_video_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.FileField(storage=video.models.YandexStorage(), upload_to=''),
        ),
    ]
