# Generated by Django 5.0.2 on 2024-03-26 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_alter_video_video_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video_url',
            new_name='video',
        ),
    ]
